### ISSUE TITLE
Where did picozero.py come from?

### ISSUE THREAD

**Issue by sgbaird** [kiate/rpi-pico-playground#1]
I'm guessing `motor_driver.py` is from https://github.com/CytronTechnologies/MAKER-PI-PICO/blob/main/Example%20Code/MicroPython/Motor%20Driver/motor_driver.py.

EDIT: just realizing this is probably the [Pico Zero library](https://picozero.readthedocs.io/en/latest/gettingstarted.html). https://github.com/RaspberryPiFoundation/picozero/blob/master/picozero/picozero.py

**Comment by kiate** [comment]
Yup, you got them right! 
And my main.py is adapted from the getting started guide by Raspberry Pi here:
[https://projects.raspberrypi.org/en/projects/get-started-pico-w/0]()
